### PR TITLE
added dividing by frobenius norm

### PR DESCRIPTION
**Pull request by brando90**
added dividing by frobenius to make sims indepedent of scale as discussed here: https://github.com/moskomule/anatome/issues/12

### CODE REVIEW

**Comment by brando90** [comment]
perhaps we need to change the places where `_zero_mean` is used to use `_matrix_normalize `.

**Comment by brando90** [comment]
new update uses the correction, not sure if other places need change however...

**Comment by brando90** [comment]
@moskomule per our discussion it seems the normalization I added is not neccessary? Just need to make sure that OP **does** normalized. Right?

**Comment by moskomule** [comment]
Yes, so I close this PR.

**Pull request closed without merging**
